#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""@package perGroupParser
Copyright (C) 2015 University of Virginia. All rights reserved.

file      perGroupParser.py
author    Shawn Chen <sc7cq@virginia.edu>
version   1.0
date      June 27, 2015

LICENSE

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or（at your option）
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details at http://www.gnu.org/copyleft/gpl.html

brief     parses log files generated by VCMTPv3 receivers on a specified
          aggregate size basis.
usage     python perGroupParser.py <logfile-to-read> <newfile-to-write>
"""


from __future__ import division
import csv
import re
import sys


def parseSizeTime(line):
    """Parses the product size and receiving time in a line.

    Parses the product size and receiving time consumed for the product in
    the given line of log file.

    Args:
        line: A line of the raw log file.

    Returns:
        (-1, -1, -1): If no valid size or time is found.
        (prodindex, prodsize, rxtime): A tuple of product index, product size
                                       and receiving time.
    """
    success_match = re.search(r'.*\[SUCCESS\].*#(\d+)', line)
    if success_match:
        sizematch = re.search(r'.*size = (\d+) bytes', line)
        timematch = re.search(r'.*time = (\d+\.\d+) seconds', line)
    if success_match and sizematch and timematch:
        prodindex = int(success_match.group(1))
        size      = int(sizematch.group(1))
        rxtime    = float(timematch.group(1))
        return (prodindex, size, rxtime)
    else:
        return (-1, -1, -1)


def parseFailure(line):
    """Parses the log to find unsuccessfully received products.

    Parses the failure message in log to find unsuccessfully received products,
    which are caused by retransmission timeouts. Since we are not able to tell
    whether a product is failed or simply out-of-sequence, we cannot detect
    failure by looking at product indices. The only reliable way is the failure
    message in log file.

    Args:
        line: A line of the raw log file.

    Returns:
        -1: If no failure message is found.
        prodindex: Index of the product which is indicated lost.
    """
    failure_match = re.search(r'.*\[FAILURE\].*#(\d+)', line)
    if failure_match:
        return int(failure_match.group(1))
    else:
        return -1


def parseMcastData(line):
    """Parses the log to find multicast data blocks.

    Parses the log to find multicast data blocks.

    Args:
        line: A line of the raw log file.

    Returns:
        -1: If no multicast block is found.
        prodindex: Index of the product which has multicast blocks.
    """
    mcast_match = re.search(r'.*\[MCAST DATA\].*#(\d+)', line)
    if mcast_match:
        return int(mcast_match.group(1))
    else:
        return -1


def parseRetxData(line):
    """Parses the log to find retransmitted data blocks.

    Parses the log to find retransmitted data blocks.

    Args:
        line: A line of the raw log file.

    Returns:
        -1: If no retransmitted block is found.
        prodindex: Index of the product which has retransmitted blocks.
    """
    retx_match = re.search(r'.*\[RETX DATA\].*#(\d+)', line)
    if retx_match:
        return int(retx_match.group(1))
    else:
        return -1


def aggregate(filename, aggregate_size):
    """Does aggregating on the given input csv.

    Does size aggregating over a csv file that contains sizes of products in
    the first column and returns the aggregate results.

    Args:
        filename: Filename of the csv file.
        aggregate_size: The size of each aggregate group.

    Returns:
        (groups, sizes): A list of aggregated groups.
    """
    groups   = []
    group    = []
    sizes    = []
    sum_size = 0
    with open(filename, 'rb') as csvfile:
        csvreader = csv.reader(csvfile, delimiter=',')
        for i, row in enumerate(csvreader):
            group.append(i)
            sum_size += int(row[0])
            if sum_size >= aggregate_size:
                groups.append(group)
                sizes.append(sum_size)
                group    = []
                sum_size = 0
        if group and sum_size:
            groups.append(group)
            sizes.append(sum_size)
    csvfile.close()
    return (groups, sizes)


def extractLog(filename):
    """Classifies the log file and extracts the lossless, complete and failed
    products.

    Classifies and extracts the lossless, complete and failed products
    separately and saves in different lists.

    Args:
        filename: Filename of the log file.

    Returns:
        (lossless, complete, failed, mcast, retx): extracted groups.
    """
    # lossless is the group endured no loss.
    lossless = set()
    # complete is the group completely received products with or without loss.
    complete = set()
    # failed is the group of not completely received products.
    failed   = set()
    # mcast is a dict containing the mcast blocks of each product.
    mcast    = {}
    # retx is a dict containing the retx blocks of each product.
    retx     = {}
    with open(filename, 'r') as logfile:
        for i, line in enumerate(logfile):
            (prodid_success, size, rxtime) = parseSizeTime(line)
            prodid_failure = parseFailure(line)
            prodid_mcast = parseMcastData(line)
            prodid_retx = parseRetxData(line)
            if prodid_success >= 0:
                lossless |= {prodid_success}
                complete |= {prodid_success}
            if prodid_failure >= 0:
                failed |= {prodid_failure}
            if prodid_mcast >= 0:
                if mcast.has_key(prodid_mcast):
                    mcast[prodid_mcast] += 1
                else:
                    mcast[prodid_mcast] = 1
            if prodid_retx >= 0:
                if retx.has_key(prodid_retx):
                    retx[prodid_retx] += 1
                else:
                    retx[prodid_retx] = 1
    logfile.close()
    retx_set = set(retx.keys())
    lossless -= retx_set
    return (lossless, complete, failed, mcast, retx)


def main(metadata, logfile, csvfile):
    """Reads the raw log file and parses it.

    Reads the raw VCMTPv3 log file, parses each line and computes throughput,
    block-based retransmission rate and FDSR over an aggregate size.

    Args:
        metadata: Filename of the metadata.
        logfile: Filename of the log file.
        csvfile : Filename of the new file to contain output results.
    """
    (tx_groups, tx_sizes) = aggregate(metadata, 1024*1024)
    (rx_noloss, rx_success, rx_failed, rx_mcast, rx_retx) = extractLog(logfile)
    #w = open(newfile, 'w+')
    #tmp_str = str(prod_based_thru) + ',' + str(reliability) + ',' \
    #        + str(retx_rate) + '\n'
    #w.write(tmp_str)
    #w.close()


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
