#!/usr/bin/env python
# -*- coding: utf-8 -*-
##
# Copyright (C) 2015 University of Virginia. All rights reserved.
#
# @file      recvLogParser.py
# @author    Shawn Chen <sc7cq@virginia.edu>
# @version   1.0
# @date      June 27, 2015
#
# @section   LICENSE
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or（at your option）
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details at http://www.gnu.org/copyleft/gpl.html
#
# @brief     parses log files generated by VCMTPv3 receivers
# @usage     python recvLogParser.py <logfile-to-read> <newfile-to-write>


import re
import sys

def main(filename, newfile):
    f = open(filename, 'r')
    w = open(newfile, 'w+')
    # parses the pattern but only takes the number
    sizes = re.findall(r'INFO:\s+(\d+)', f.read())
    for size in sizes:
        w.write(size + '\n')
    f.close()
    w.close()

# takes 2 command line arguments, first is log file name, second is new file to
# contain the parsed results.
if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
